#!/usr/bin/env bash

if [[ ! $@ ]]; then
    python3 -m launch_control
else
    if [[ "$@" =~ ssh ]]
    then
        $(python3 -m launch_control $@) 
    else
        python3 -m launch_control $@
    fi
    
fi